#println("module JNI")
#println("import ..JavaCall: JNIEnv, JavaVM, jbyte, jchar, jshort, jint, jlong, jsize, jdouble, jfloat, jboolean")
#for t in ["jobject", "jclass", "jthrowable", "jweak", "jmethodID", "jfieldID",  "jstring", "jarray", "JNINativeMethod"]
#println("$t = Ptr{Nothing}")
#end
#for t in ["object", "boolean", "byte", "short", "int", "long", "float", "double", "char"]
#println("j$(t)Array = Ptr{Nothing}")
#end
#println("jvalue = Int64")
#println()
println("# === Below Generated by ",PROGRAM_FILE," ===")
println("")

# JNI methods that may execute arbitrary Java code or trigger GC pin/unpin
# operations that the JVM may make slow. Annotate ccalls into these with
# `gc_safe = true` (Julia 1.12+) so Julia's GC can proceed concurrently
# while the call is in flight. See the spec's "gc_safe = true audit"
# table for full rationale.
const GC_SAFE_PREFIXES = [
    "Call",
    "GetStatic", "SetStatic",
    "Get", "Set",
    "GetBooleanArrayElements", "GetByteArrayElements", "GetCharArrayElements",
    "GetShortArrayElements", "GetIntArrayElements", "GetLongArrayElements",
    "GetFloatArrayElements", "GetDoubleArrayElements",
    "ReleaseBooleanArrayElements", "ReleaseByteArrayElements", "ReleaseCharArrayElements",
    "ReleaseShortArrayElements", "ReleaseIntArrayElements", "ReleaseLongArrayElements",
    "ReleaseFloatArrayElements", "ReleaseDoubleArrayElements",
    "FindClass", "DefineClass",
    "GetMethodID", "GetStaticMethodID", "GetFieldID", "GetStaticFieldID",
    "FromReflectedMethod", "FromReflectedField",
    "NewObject",
    "ToReflectedMethod", "ToReflectedField",
]

const GC_UNSAFE_NAMES = Set([
    "GetPrimitiveArrayCritical", "ReleasePrimitiveArrayCritical",
    "GetStringCritical", "ReleaseStringCritical",
])

is_gc_safe(fname::AbstractString) = begin
    fname in GC_UNSAFE_NAMES && return false
    any(startswith(fname, p) for p in GC_SAFE_PREFIXES)
end

function arg_name(m)
  m.captures[3]
end

function arg_value(m)
  #if m.captures[2] == "*" && m.captures[1] == "char" return "String($(m.captures[3]))" end
  if m.captures[3] == "env"
      "penv"
  else
     m.captures[3]
  end
end

decl_arg_type(m) = decl_arg_type(m.captures[1], m.captures[2])
ccall_arg_type(m; r=false) = ccall_arg_type(m.captures[1], m.captures[2], r=r)

# Remap C type names to their Julia primitive type names where they differ.
# `jvalue` is the only one in Phase 2: the C union type maps to Julia's
# primitive type `JValue` (CamelCase) — see src/JNI.jl. The lowercase form
# is the encoder function name in core.jl, not the type.
remap_t(t) = t == "jvalue" ? "JValue" : t

function decl_arg_type(t, s)
  t = remap_t(t)
  if s == "*"
    if t == "char"
      return "AnyString"
    elseif t == "void"
      return "Ptr{Nothing}"
    elseif t == "JNIEnv"
      return "Ptr{JNIEnv}"
    else
      return "Array{$t,1}"
#      return "Ptr{$t}"
    end
  elseif t == "jsize" #|| t == "jint" || t == "jlong" || t == "jshort" || t == "jbyte"
    return Integer
  elseif t == "jobject"
    return "jobject_arg"
  elseif t == "jobjectArray"
    return "jobjectArray_arg"
  end

  if t == "void"
    return "Nothing"
  end

  return s == "" ? t : "Array{$t,1}"
#  return s == "" ? t : "Ptr{$t}"
end

function ccall_arg_type(t, s; r=false)
  t = remap_t(t)
  if s == "*"
    if t == "char"
      return "Cstring"
    elseif t == "void"
      return "Ptr{Nothing}"
    elseif t == "JNIEnv"
      return "Ptr{JNIEnv}"
    else
      return "Ptr{$t}"
    end
  end

  if t == "void"
    return "Nothing"
  end

  # No asterisk: type
  # If return type, Ptr
  # Else Array
  return s == "" ? t : r ? "Ptr{$t}" : "Array{$t,1}"
end

# julia_arg(m) = string(arg_name(m), "::", decl_arg_type(m))
function julia_arg(m)
    if arg_name(m) == "isCopy"
        "isCopy::PtrIsCopy"
    elseif arg_name(m) == "elems"
        string(arg_name(m), "::", "Ptr{$(m.captures[1])}") 
    else
        string(arg_name(m), "::", decl_arg_type(m))
    end
end

for line in open(readlines, "jnienv.jl", "r")
  # m: match comments
  # Example:
  # # jclass ( *GetSuperclass) (JNIEnv *env, jclass sub);
  # Group 1: Return type ((?:void|char|j\w+)) "jclass"
  # Group 2: Asterisk (\**) ""
  # Group 3: Function name (\w+) "GetSuperclass"
  # Group 4: Arguments \((.*)\) "JNIEnv *env, jclass sub"
  m = match(r"\# \s* (?:const\s*)? ((?:void|char|j\w+)) \s* (\**) \s* \( \s* \* (\w+) \s* \) \s* \((.*)\) \s* ;"x, line)
  if m === nothing continue end

  # Ignore functions with variable argument syntax
  # Only process vararg functions that end in A
  if occursin("...", m.captures[4]) continue end
  if occursin("va_list", m.captures[4]) continue end

  # Get return type
  rtype = ccall_arg_type(m.captures[1], m.captures[2], r=true)

  # Function name
  fname = m.captures[3]
  # Split arguments
  args = split(m.captures[4], ",")

  # mm: Analyze arguments
  # Example: [1] "JNIEnv *env", [2] "jclass sub"
  # Group 1: Argument type ((?:void|j\w+|char|JNI\w+|JavaVM))
  # Group 2: Asterisk (\**)
  # Group 3: Argument name (\w+)
  mm = map(x->match(r"^\s* (?:const\s+)? \s* ((?:void|j\w+|char|JNI\w+|JavaVM)) \s*? (\**) \s* (\w+) \s*$"x, x), args)

  # skip the JNIEnv arg for julia since it is passed explicitly by callers.
  # Phase 2: env is a required argument, no default. Callers obtain env
  # via `with_env(f) do env ... end` from src/env.jl.
  julia_args = join(push!(map(julia_arg, mm)[2:end], "penv::Ptr{JNIEnv}"), ", ")
  arg_types = join(map(ccall_arg_type, mm), ", ")
  arg_names = join(map(arg_value, mm), ", ")

  # Commented out export command
  # print("#export $fname\n")
  if is_gc_safe(fname)
      typed_args = String[]
      for (name, typ) in zip(map(arg_value, mm)[2:end], split(arg_types, ", ")[2:end])
          push!(typed_args, "$name::$typ")
      end
      pushfirst!(typed_args, "penv::Ptr{JNIEnv}")
      # gc_safe must come BEFORE the call expression in @ccall (Julia 1.12 c.jl
      # ccall_macro_parse expects exprs[1] to be the gc_safe option and
      # exprs[2] to be the call). Putting it after produces
      # ArgumentError: "@ccall option must be `gc_safe=true` or `gc_safe=false`".
      #
      # The `\$(jniref[].FNAME)` interpolation is required: without it,
      # @ccall parses `jniref[].FNAME(...)` as `library.symbol(...)` and
      # tries to dlopen jniref[] as a library handle. Interpolation
      # evaluates the expression to a Ptr (the function pointer) and
      # passes it as the call target.
      print("$fname($julia_args) =\n  @ccall gc_safe=true \$(jniref[].$(fname))(",
            join(typed_args, ", "), ")::$rtype\n\n")
  else
      print("$fname($julia_args) =\n  ccall(jniref[].$(fname), $rtype, ($arg_types,), $arg_names)\n\n")
  end
end

# println("end")
println("")
println("# === Above Generated by ",PROGRAM_FILE," ===")
